use db_loja;
select * from produtos;

INSERT INTO produtos (nome_produto, tipo_produto, cor_produto, tamanho_produto, marca_produto, quantidade_produto, preco_produto) VALUES
('Camiseta Básica Algodão', 'Camiseta', 'Branca', 'M', 'Hering', 50, 39.90),
('Camiseta Básica Algodão', 'Camiseta', 'Preta', 'G', 'Hering', 40, 39.90),
('Camiseta Estampada', 'Camiseta', 'Azul', 'M', 'Nike', 30, 59.90),
('Camiseta Polo', 'Camiseta', 'Verde', 'P', 'Lacoste', 20, 199.90),
('Calça Jeans Slim', 'Calça', 'Azul', '42', 'Levi’s', 25, 249.90),
('Calça Jeans Skinny', 'Calça', 'Preta', '40', 'Levi’s', 15, 259.90),
('Calça Moletom', 'Calça', 'Cinza', 'M', 'Adidas', 35, 149.90),
('Bermuda Jeans', 'Bermuda', 'Azul Claro', '44', 'Colcci', 20, 129.90),
('Bermuda Moletom', 'Bermuda', 'Preta', 'M', 'Nike', 25, 119.90),
('Jaqueta Jeans', 'Jaqueta', 'Azul', 'G', 'Levi’s', 10, 299.90),
('Jaqueta Corta-Vento', 'Jaqueta', 'Preta', 'M', 'Adidas', 15, 349.90),
('Jaqueta Couro', 'Jaqueta', 'Marrom', 'G', 'Ellus', 8, 499.90),
('Vestido Curto', 'Vestido', 'Vermelho', 'M', 'Zara', 20, 199.90),
('Vestido Longo', 'Vestido', 'Azul', 'G', 'Zara', 15, 249.90),
('Saia Jeans', 'Saia', 'Azul', '38', 'Colcci', 18, 139.90),
('Saia Midi', 'Saia', 'Preta', '40', 'Zara', 12, 159.90),
('Camisa Social', 'Camisa', 'Branca', 'M', 'Dudalina', 25, 229.90),
('Camisa Social', 'Camisa', 'Azul Claro', 'G', 'Dudalina', 20, 229.90),
('Camisa Xadrez', 'Camisa', 'Vermelha', 'M', 'Hering', 30, 149.90),
('Blusa de Frio', 'Blusa', 'Cinza', 'M', 'Gap', 20, 199.90),
('Blusa Cropped', 'Blusa', 'Rosa', 'P', 'Forever 21', 25, 89.90),
('Blusa Manga Longa', 'Blusa', 'Preta', 'G', 'Hering', 30, 99.90),
('Short Jeans', 'Short', 'Azul', '36', 'Colcci', 20, 119.90),
('Short Moletom', 'Short', 'Cinza', 'M', 'Nike', 25, 99.90),
('Casaco de Lã', 'Casaco', 'Bege', 'M', 'Zara', 10, 399.90),
('Casaco Trench Coat', 'Casaco', 'Preto', 'G', 'Zara', 8, 499.90),
('Camisa Polo', 'Camisa', 'Branca', 'M', 'Lacoste', 15, 199.90),
('Camisa Polo', 'Camisa', 'Azul', 'G', 'Lacoste', 12, 199.90),
('Regata Básica', 'Regata', 'Preta', 'M', 'Hering', 40, 39.90),
('Regata Estampada', 'Regata', 'Branca', 'G', 'Nike', 30, 59.90);
